services:
  - type: web
    name: docx-constructor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT -w 2 --threads 8
    autoDeploy: true
